baseURL: https://uniget.dev
title: uni(versal)get
theme:
- github.com/1bl4z3r/hermit-V2
languageCode: en-us

params:
  author: Nicholas Dille
  homeSubtitle: The universal installer and updater for (container) tools
  homeSubtitlePrinter: true
  themeColor: "#494f5c"
  footerCopyright: ' &#183; Nicholas Dille - licensed under <a href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>'
  social:
  - name: github
    url: https://github.com/uniget-org/cli

menu:
  main:
  - identifier: tools
    name: ğŸš€ Quickstart ğŸš€
    url: https://docs.uniget.dev/installation/
    weight: 50
  - identifier: tools
    name: ğŸ§° Included tools ğŸ§°
    url: https://tools.uniget.dev
    weight: 70
  - identifier: docs
    name: ğŸ“˜ Documentation ğŸ“˜
    url: https://docs.uniget.dev
    weight: 100
  - identifier: security
    name: ğŸ”’ Report a security vulnerability ğŸ”’
    url: https://github.com/uniget-org/cli/issues/new/choose
    weight: 200
  - identifier: bug
    name: ğŸ› Report a bug ğŸ›
    url: https://github.com/uniget-org/cli/issues/new/choose
    weight: 300
  - identifier: enhancement
    name: â­ Submit a feature suggestion â­
    url: https://github.com/uniget-org/cli/issues/new/choose
    weight: 400
  - identifier: contribute
    name: âœ Become a contributor âœ
    url: https://github.com/uniget-org/cli/blob/main/CONTRIBUTING.md
    weight: 500